#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

path_to_this_dir="$(pwd)"
name_of_this_dir="$(basename "${path_to_this_dir}")"
image_name="${name_of_this_dir}"
dockerfile=${2:-"Dockerfile"}

build () {
  docker image build \
    --tag "${image_name}" \
    --file "${dockerfile}" .
}

run () {
  docker container run \
  --rm \
  --env-file .env \
  --publish=8000:80 \
  "${image_name}"
}

help_message () {
  cat "$(dirname "${BASH_SOURCE[0]}")/help.txt"
}

read_options () {
  while test $# -gt 0; do
    case "$1" in
      help)
        help_message
        exit 0
        ;;
      build)
        build
        exit 0
        ;;
      run)
        run
        exit 0
        ;;
      *)
        help_message
        break
        ;;
    esac
  done
}

main () {
  if [ $# -eq 0 ]; then
      build
      run
  fi
  read_options "$@"
}

main "$@"
